name: Generate and Deploy Documentation

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.*
        
    - name: Install DocFX
      run: |
        dotnet tool install -g docfx
        echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build project
      run: dotnet build --no-restore
      
    - name: Prepare DocFX
      run: |
        mkdir -p docfx_project
        docfx init -q -o docfx_project
        
    - name: Configure DocFX
      run: |
        cat > docs/docfx.json << EOF
        {
          "metadata": [
            {
              "src": [
                {
                  "files": [
                    "src/Quantum/**.csproj",
                    "src/Bridge/**.csproj"
                  ],
                  "src": ".."
                }
              ],
              "dest": "api",
              "disableGitFeatures": false,
              "disableDefaultFilter": false
            }
          ],
          "build": {
            "content": [
              {
                "files": [
                  "api/**.yml",
                  "api/index.md"
                ]
              },
              {
                "files": [
                  "articles/**.md",
                  "articles/**/toc.yml",
                  "toc.yml",
                  "*.md"
                ]
              }
            ],
            "resource": [
              {
                "files": [
                  "images/**"
                ]
              }
            ],
            "overwrite": [
              {
                "files": [
                  "apidoc/**.md"
                ],
                "exclude": [
                  "obj/**",
                  "_site/**"
                ]
              }
            ],
            "dest": "../docs",
            "globalMetadataFiles": [],
            "fileMetadataFiles": [],
            "template": [
              "default"
            ],
            "postProcessors": [],
            "markdownEngineName": "markdig",
            "noLangKeyword": false,
            "keepFileLink": false,
            "cleanupCacheHistory": false,
            "disableGitFeatures": false
          }
        }
        EOF
        
        # Copy README.md for index
        cp ../README.md docfx_project/index.md
        
        # Create basic TOC
        cat > docfx_project/toc.yml << EOF
        - name: Home
          href: index.md
        - name: API Documentation
          href: api/
          homepage: api/index.md
        - name: Articles
          href: articles/
        EOF
        
        # Create API index
        mkdir -p docfx_project/api
        cat > docfx_project/api/index.md << EOF
        # EasyQ API Documentation
        
        Welcome to the API documentation for EasyQ, a quantum computing framework for regular developers.
        
        ## Namespaces
        
        * [EasyQ.Bridge](EasyQ.Bridge.html) - Developer-friendly APIs for quantum computing
        * [EasyQ.Bridge.Search](EasyQ.Bridge.Search.html) - Search functionality using quantum algorithms
        * [EasyQ.Bridge.Cryptography](EasyQ.Bridge.Cryptography.html) - Cryptographic functionality using quantum properties
        * [EasyQ.Quantum](EasyQ.Quantum.html) - Core quantum operations
        EOF
        
        # Create basic article structure
        mkdir -p docfx_project/articles
        cat > docfx_project/articles/intro.md << EOF
        # Introduction to EasyQ
        
        EasyQ makes quantum computing accessible to regular developers without requiring specialized knowledge of quantum mechanics or quantum computing principles.
        
        ## Getting Started
        
        To use EasyQ in your project:
        
        1. Install the EasyQ package
        2. Add the necessary using statements
        3. Create instances of the quantum operation classes you need
        
        ## Examples
        
        Check out the [examples in our test suite](https://github.com/yourusername/EasyQ/tree/main/tests) to see EasyQ in action.
        EOF
        
        cat > docfx_project/articles/toc.yml << EOF
        - name: Introduction
          href: intro.md
        EOF
        
    - name: Generate documentation
      run: |
        cd docfx_project
        docfx metadata
        docfx build
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        force_orphan: true  # Use a single-branch approach
