name: Generate and Deploy Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows you to run this workflow manually from the Actions tab

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup .NET versions
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.0.x
          9.0.x
        
    - name: Install DocFX
      run: |
        dotnet tool install -g docfx
        echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
        
    # We need to build the projects for DocFX to properly resolve references
    - name: Build projects for documentation
      run: |
        dotnet build src/Quantum/Quantum.csproj -f net6.0
        dotnet build src/Bridge/Bridge.csproj -f net9.0
      
    - name: Prepare docs directory
      run: |
        mkdir -p docs
        mkdir -p docs/api
        mkdir -p docs/articles
        mkdir -p docs/images
        
    - name: Configure DocFX
      run: |
        # Create docfx.json in the docs directory
        cat > docs/docfx.json << EOF
        {
          "metadata": [
            {
              "src": [
                {
                  "files": [
                    "src/Quantum/Quantum.csproj"
                  ],
                  "src": "..",
                  "properties": {
                    "TargetFramework": "net6.0"
                  }
                }
              ],
              "dest": "api/quantum",
              "includePrivateMembers": false,
              "disableGitFeatures": false,
              "disableDefaultFilter": false
            },
            {
              "src": [
                {
                  "files": [
                    "src/Bridge/Bridge.csproj"
                  ],
                  "src": "..",
                  "properties": {
                    "TargetFramework": "net9.0"
                  }
                }
              ],
              "dest": "api/bridge",
              "includePrivateMembers": false,
              "disableGitFeatures": false,
              "disableDefaultFilter": false
            }
          ],
          "build": {
            "content": [
              {
                "files": [
                  "api/**.yml",
                  "api/index.md"
                ]
              },
              {
                "files": [
                  "articles/**.md",
                  "articles/**/toc.yml",
                  "toc.yml",
                  "*.md"
                ]
              }
            ],
            "resource": [
              {
                "files": [
                  "images/**"
                ]
              }
            ],
            "overwrite": [
              {
                "files": [
                  "apidoc/**.md"
                ],
                "exclude": [
                  "obj/**",
                  "_site/**"
                ]
              }
            ],
            "dest": "_site",
            "globalMetadataFiles": [],
            "fileMetadataFiles": [],
            "template": [
              "default"
            ],
            "postProcessors": [],
            "markdownEngineName": "markdig",
            "noLangKeyword": false,
            "keepFileLink": false,
            "cleanupCacheHistory": false,
            "disableGitFeatures": false
          }
        }
        EOF
        
        # Copy README.md for index
        cp README.md docs/index.md
        
        # Create basic TOC
        cat > docs/toc.yml << EOF
        - name: Home
          href: index.md
        - name: API Documentation
          href: api/
          homepage: api/index.md
        - name: Articles
          href: articles/
        EOF
        
        # Create API index
        cat > docs/api/index.md << EOF
        # EasyQ API Documentation
        
        Welcome to the API documentation for EasyQ, a quantum computing framework for regular developers.
        
        ## Namespaces
        
        ### Quantum Layer
        * [EasyQ.Quantum](quantum/EasyQ.Quantum.html) - Core quantum operations
        * [EasyQ.Quantum.Search](quantum/EasyQ.Quantum.Search.html) - Quantum search algorithms
        * [EasyQ.Quantum.Cryptography](quantum/EasyQ.Quantum.Cryptography.html) - Quantum cryptography operations
        
        ### Bridge Layer
        * [EasyQ.Bridge](bridge/EasyQ.Bridge.html) - Developer-friendly APIs for quantum computing
        * [EasyQ.Bridge.Search](bridge/EasyQ.Bridge.Search.html) - Search functionality using quantum algorithms
        * [EasyQ.Bridge.Cryptography](bridge/EasyQ.Bridge.Cryptography.html) - Cryptographic functionality using quantum properties
        EOF
        
        # Create basic article structure
        cat > docs/articles/intro.md << EOF
        # Introduction to EasyQ
        
        EasyQ makes quantum computing accessible to regular developers without requiring specialized knowledge of quantum mechanics or quantum computing principles.
        
        ## Getting Started
        
        To use EasyQ in your project:
        
        1. Install the EasyQ package
        2. Add the necessary using statements
        3. Create instances of the quantum operation classes you need
        
        ## Examples
        
        Check out the [examples in our test suite](https://github.com/yourusername/EasyQ/tree/main/tests) to see EasyQ in action.
        EOF
        
        cat > docs/articles/toc.yml << EOF
        - name: Introduction
          href: intro.md
        EOF
        
    - name: Generate documentation
      run: |
        cd docs
        docfx metadata
        docfx build
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_site
        force_orphan: true  # Use a single-branch approach
